modLoader="javafml"
loaderVersion="[34,)"
license="LGPL 3"
issueTrackerURL="https://github.com/GoryMoon/PlayerMobs"

[[mods]]
    modId="playermobs"
    version="${file.jarVersion}"
    displayName="Player Mobs"
    #updateJSONURL="http://myurl.me/"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/player-mobs"
    #logoFile="examplemod.png"
    credits="Thanks to Headcrumbs for the base idea."
    authors="GoryMoon"
    description='''
Adds a mob that has other players skin.
'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
